<%@ Page Title="" Language="C#" MasterPageFile="~/MP1.Master" AutoEventWireup="true" CodeBehind="FindUsers.aspx.cs" Inherits="MITT.FindUsers" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:Label ID="lblUserCount" runat="server"></asp:Label>
    <br />
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns = "false" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="true" DataKeyNames="ID" 
        onrowcancelingedit="GridView1_CancelEditing" 
        onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing" 
        onrowupdating="GridView1_RowUpdating" 
        onselectedindexchanged="GridView1_SelectedIndexChanged" 
        BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" 
        CellPadding="2" ForeColor="Black" GridLines="None" 
        onrowdatabound="GridView1_RowDataBound">
        <AlternatingRowStyle BackColor="PaleGoldenrod" />
        <FooterStyle BackColor="Tan" />
        <HeaderStyle BackColor="Tan" Font-Bold="True" />
        <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" 
            HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
        <SortedAscendingCellStyle BackColor="#FAFAE7" />
        <SortedAscendingHeaderStyle BackColor="#DAC09E" />
        <SortedDescendingCellStyle BackColor="#E1DB9C" />
        <SortedDescendingHeaderStyle BackColor="#C2A47B" />
        <Columns>
            <asp:BoundField DataField="id" ReadOnly="true" HeaderText="UserId" />
            <asp:BoundField DataField="name" HeaderText="Name" />
            <asp:BoundField DataField="email" HeaderText="Email Address" />
            <asp:BoundField DataField="companyname" HeaderText="Company Name" />
            <asp:BoundField DataField="phoneNo" HeaderText="Contact Phone" />
            <%-- 
            <asp:BoundField DataField="roles" HeaderText="User Type" />
            --%>
            <asp:TemplateField HeaderText="UserType">
            <ItemTemplate>
            <asp:Label ID="lblRoles" runat="server" Text='<%# Eval("Roles") %>' Visible = "false" />
            <asp:DropDownList runat="server" 
               id="ddlRoles" AutoPostBack="true" 
               OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
                <asp:ListItem Text="Administrator" value="0"></asp:ListItem>
                 <asp:ListItem Text="Support Rep" value="1"></asp:ListItem>  
                 <asp:ListItem Text="General User" value="2"></asp:ListItem> 
            </asp:DropDownList> 
            </ItemTemplate>
        </asp:TemplateField>
        </Columns>
    </asp:GridView>
    <br />
    <asp:Label ID="lblErrMsg" runat="server" 
        Text="Error on page, please check the logs"></asp:Label>
</asp:Content>
