<%@ Page Title="" Language="C#" MasterPageFile="~/MP1.Master" AutoEventWireup="true" CodeBehind="findCategory.aspx.cs" Inherits="MITT.findCat" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:Label ID="lblQCount" runat="server"></asp:Label>
    <div style = "height:30px;width:600px; margin:0;padding:0">
    <table cellspacing="0" cellpadding = "0" rules="all" border="1" id="tblHeader"
    bgcolor="#00FF00"
    style="font-family:Arial;font-size:10pt;width:617px;color:white;
    border-collapse:collapse;height:100%;">
    <tr>
        <td style ="width:100px;text-align:center">Modify</td>
       <td style ="width:75px;text-align:center">Queue No</td>
       <td style ="width:350px;text-align:center">Queue Name</td>
       <td style ="width:100px;text-align:center">isActive</td>
       
    </tr>
</table>
</div>
<div style ="height:200px; width:617px; overflow:auto;">
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"
    style="height:200px; overflow:scroll" ShowHeader = "false"
            BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" 
            CellPadding="2" ForeColor="Black" GridLines="None" 
            HorizontalAlign="Center"
    NullDisplayText="No Data" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" datakeynames = "ID" 
        onrowdeleting="GridView1_RowDeleting" 
        onselectedindexchanged="GridView1_SelectedIndexChanged" 
        onrowcancelingedit="GridView1_cancelEditing" 
        onrowediting="GridView1_RowEditing" onrowupdating="GridView1_RowUpdating">
        <AlternatingRowStyle BackColor="PaleGoldenrod" />
        <Columns>
            <asp:BoundField DataField="id" ReadOnly="true" ItemStyle-Width = "75px" ItemStyle-cssClass= "TACenter" />
            <asp:BoundField DataField="Name" ItemStyle-Width = "350px" ItemStyle-cssClass= "TACenter" />
            <asp:BoundField DataField="isActive" ItemStyle-Width = "100px" ItemStyle-cssClass= "TACenter" />
        </Columns>
    </asp:GridView>
    </div>
</asp:Content>
